/** Main layout.tsx */
import type { Metadata } from "next";
import { root } from "@actionishope/shelley/styles";
import "@/styles";
import { Header } from "@/components/Header";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={root} data-theme="dark">
      <Head>
        <meta name="theme-color" content="#75eaff" />
      </Head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
